### ISSUE TITLE
Is record restriction correct?

### ISSUE THREAD

**Issue by Guest0x0** [7sharp9/write-you-an-inference-in-fsharp#11]
It feels good to find a type system fan on Github XD.
According to [this paper](http://citeseerx.ist.psu.edu/viewdoc/download;jsessionid=01CF095B33374F010E30BFB1F6AD0021?doi=10.1.1.380.2653&rep=rep1&type=pdf) (and perhaps other papers on row polymorphism) record restriction requires some sort of constraint.  For instance, the following expression
`fun r -> (r - x).x`
 should be rejected, so does
`fun r -> (r.x, { x = 1 | r })`
But I am not aware of something similar in the implementation. So is record restriction correct here, or if you have used some techniques out of my knowledge?

**Comment by 7sharp9** [comment]
Hmm, I would have to check its been more than a year since I thought about this code :-)

Theres are restrictions but I forget what they are now.

**Comment by 7sharp9** [comment]
Theres no predicate restriction, if I remember correct its based on: [Extensible records with scoped labels](http://research.microsoft.com/apps/pubs/default.aspx?id=65409)

**Comment by Guest0x0** [comment]
Oh, I see. I have not spotted this paper yet. I think your code should be correct, I am not aware of techniques supporting duplicated labels before.
